import type { Config } from 'tailwindcss'

const config: Config = {
  content: [
    './pages/**/*.{js,ts,jsx,tsx,mdx}',
    './components/**/*.{js,ts,jsx,tsx,mdx}',
    './app/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
      colors: {
        navy: '#0E4573',
        teal: '#186B8B',
        sage: '#4C8386',
        offwhite: '#F3F8FB',
        'on-surface-variant': '#42474f',
        'secondary': '#0d6686',
        'surface-tint': '#336190',
        'tertiary-container': '#094b4e',
        'on-secondary': '#ffffff',
        'primary-fixed-dim': '#9fcaff',
        'on-secondary-fixed': '#001e2b',
        'on-tertiary-fixed': '#002021',
        'primary-fixed': '#d1e4ff',
        'surface-container-highest': '#dee3e6',
        'secondary-fixed': '#c1e8ff',
        'background': '#f5fafd',
        'on-surface': '#171c1f',
        'outline': '#727780',
        'surface-dim': '#d6dbde',
        'surface-container': '#eaeff2',
        'on-primary': '#ffffff',
        'on-primary-fixed-variant': '#154977',
        'inverse-surface': '#2c3134',
        'secondary-container': '#95dbff',
        'tertiary-fixed-dim': '#98d0d3',
        'on-error': '#ffffff',
        'on-tertiary-fixed-variant': '#104f52',
        'tertiary-fixed': '#b4edf0',
        'on-background': '#171c1f',
        'on-primary-fixed': '#001d36',
        'on-error-container': '#93000a',
        'surface-variant': '#dee3e6',
        'inverse-primary': '#9fcaff',
        'surface-bright': '#f5fafd',
        'tertiary': '#003335',
        'on-tertiary-container': '#82babd',
        'on-secondary-fixed-variant': '#004d66',
        'secondary-fixed-dim': '#8acff3',
        'on-tertiary': '#ffffff',
        'primary-container': '#0e4573',
        'surface-container-lowest': '#ffffff',
        'on-secondary-container': '#006181',
        'error-container': '#ffdad6',
        'surface-container-low': '#eff4f7',
        'outline-variant': '#c2c7d0',
        'surface': '#f5fafd',
        'on-primary-container': '#87b3e7',
        'primary': '#002e53',
        'inverse-on-surface': '#ecf1f4',
        'error': '#ba1a1a',
        'surface-container-high': '#e4e9ec',
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        lg: '0.25rem',
        xl: '0.5rem',
        full: '0.75rem',
      },
      spacing: {
        'container-max': '1280px',
        'gutter': '24px',
        'margin-mobile': '16px',
        'stack-sm': '8px',
        'stack-md': '24px',
        'stack-lg': '64px',
      },
      fontFamily: {
        'headline-xl': ['Sora'],
        'headline-lg': ['Sora'],
        'headline-lg-mobile': ['Sora'],
        'headline-md': ['Sora'],
        'body-lg': ['Hanken Grotesk'],
        'body-md': ['Hanken Grotesk'],
        'label-caps': ['Hanken Grotesk'],
      },
      fontSize: {
        'headline-xl': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-lg-mobile': ['28px', { lineHeight: '34px', fontWeight: '700' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.1em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
export default config
