export const corridors = [
  {
    id: 'northern',
    slug: 'northern-corridor',
    label: 'Northern Corridor',
    title: 'Northern Corridor — Volcanoes National Park',
    subtitle: 'The heart of Rwanda\'s conservation efforts and the majestic home of the mountain gorillas.',
    tagline: 'Explore the Highlands',
    packages: [
      { name: 'Gorilla Trekking', featured: true,
        desc: 'Witness the legendary Mountain Gorillas in their natural habitat. Rwanda currently has 12 habituated gorilla families available to visit. The annual "Kwita Izina" baby gorilla naming ceremony, held since 2005, is rooted in a centuries-old Rwandan tradition. Only 8 people per gorilla family per day, visits capped at one hour, minimum age of 15.',
        rules: ['Maintain 10m distance', 'Maximum 1 hour observation', 'No flash photography'],
        image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjINUSRFv7UittYpBJO6AAHXe3F0BQVZgbbW94jSc03juQ6_Hk20gQl-kYIK4-cWlQm7QCS1zjMzw75Ro6kZZWKAlB3-z9P-oqN_1ETtbsKB8G0YdUwSjzmxd5qJuj-zDhNKTAiklEmyeJ5C6SkvGddnafz_nokaD2P7UO4BPEzfpQmircKY934UXriV3-cwHqoKKIkDoht6ayxhfzkEDio8uVly4bhWBpP9k8MYyzt4kHA_Iwa07q_uX7hreGyFffWbqZwvildIg',
        price: 'From $1,500' },
      { name: 'Karisimbi Hiking', desc: 'Climb the highest of the Virunga volcanoes at 4,507m for a challenging multi-day trek.', image: '' },
      { name: 'Bisoke Hiking', desc: 'Ascend to the stunning crater lake at the summit of Mount Bisoke.', image: '' },
      { name: 'Gahinga Hiking', desc: 'Explore the extinct volcano with its unique bamboo forest ecosystem.', image: '' },
      { name: 'Sabyinyo Climbing', desc: 'Trek to the "Old Man\'s Teeth" — a challenging climb across three countries.', image: '' },
      { name: 'Iby\'Iwacu Cultural Village', desc: 'Immerse yourself in traditional Rwandan village life and customs.', image: '' },
      { name: 'Gorilla Museum', desc: 'Learn about conservation history and gorilla research at the base of the volcanoes.', image: '', featured: false },
      { name: 'Coffee Farm Tour Experience', desc: 'Visit local coffee plantations and learn the crop-to-cup process.', image: '', featured: false },
      { name: 'Twin Lakes', desc: 'Visit Lake Burera and Lake Ruhondo — two stunning crater lakes with breathtaking views.', image: '', featured: false },
    ],
  },
  {
    id: 'southern',
    slug: 'southern-corridor',
    label: 'Southern Corridor',
    title: 'Southern Corridor',
    subtitle: 'A deep dive into Rwanda\'s royal history, cultural heritage, and the somber lessons of Murambi.',
    tagline: 'Southern History',
    packages: [
      { name: 'King\'s Palace', desc: 'Visit the restored royal palace in Nyanza, the seat of the ancient Rwandan monarchy.', image: '', featured: false },
      { name: 'Ethnographic Museum', desc: 'Explore one of Africa\'s finest ethnographic museums in Huye, showcasing Rwandan cultural artifacts.', image: '', featured: false },
      { name: 'Coffee Tour Experience', desc: 'Travel to the southern coffee-growing regions for a unique agrotourism experience.', image: '', featured: false },
      { name: 'Murambi Genocide Memorial', desc: 'A dignified place of remembrance. We approach this visit with profound respect.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCwf3PRg9j3IC02mQskZkza73URTjSTfDZUcV4z3V2cAVXGunWLxCO1Y3pQmfdWr2vs4MMiHF4ScchzEE5Z-HE4L9rt2Mo9AwCwUbTN2trAW54-cRziYHlf7xBgzzveYGNQr7GKgA_foeN-9ahqQrvDKqJhKtLDtM2upZtbQ7us1om5Big279t2K4AjbLcC4AsQ5zAlYlR-mTvuxw0xd6BTtg9vtoqK_NTJcF90JBi7Q40Xss11ae0ky6VZfqh4s_l1L92f6uSPdM8', memorial: true },
    ],
  },
  {
    id: 'nyungwe',
    slug: 'nyungwe-forest',
    label: 'Nyungwe Forest',
    title: 'Nyungwe Forest National Park',
    subtitle: 'One of Africa\'s oldest rainforests, home to 13 primate species and the famous canopy walkway.',
    tagline: 'Ancient Rainforest',
    packages: [
      { name: 'Chimpanzee Trekking', desc: 'Track habituated chimpanzee troops through the ancient rainforest.', image: '' },
      { name: 'Nyungwe Guided Nature Walks', desc: 'Explore diverse trails through one of Africa\'s oldest rainforests.', image: '' },
      { name: 'Nyungwe Bird Watching', desc: 'Spot over 300 bird species, including 26 endemics to the Albertine Rift.', image: '' },
      { name: 'Nyungwe Canopy Walk', desc: 'Walk among the clouds on Africa\'s highest canopy walkway, suspended 50m above the forest floor.', image: '' },
      { name: 'Tropical Waterfall Guided Hike', desc: 'Hike through dense forest to discover stunning waterfalls.', image: '' },
      { name: 'Congo Nile Divide Guided Hike', desc: 'Trek along the continental divide separating the Congo and Nile basins.', image: '' },
    ],
  },
  {
    id: 'kivu',
    slug: 'kivu-belt-road',
    label: 'Kivu Belt Road',
    title: 'Kivu Belt Road',
    subtitle: 'The most beautiful road in Rwanda, winding along the sapphire waters and emerald islands of Lake Kivu.',
    tagline: 'Scenic Drive',
    packages: [
      { name: 'Boat Experience on Lake Kivu', desc: 'Sunset cruises and island-hopping adventures from Karongi and Rubavu.', image: '' },
      { name: 'Island Visits on Lake Kivu', desc: 'Explore the serene islands of Lake Kivu from Karongi.', image: '' },
    ],
  },
  {
    id: 'eastern',
    slug: 'eastern-province',
    label: 'Eastern Province',
    title: 'Eastern Province — Akagera National Park',
    subtitle: 'Savannah safaris in Rwanda\'s Big Five national park. Boat trips on Lake Ihema.',
    tagline: 'Savannah Wilderness',
    packages: [
      { name: 'Akagera National Park', desc: 'Witness the Big Five in Central Africa\'s largest protected wetland. Game drives and boat safaris available.', image: '' },
    ],
  },
  {
    id: 'kigali',
    slug: 'kigali',
    label: 'Kigali City',
    title: 'Kigali & Historical Legacies',
    subtitle: 'Remembrance, reflection, and the vibrant culture of Africa\'s cleanest city.',
    tagline: 'Remembrance & Reflection',
    packages: [
      { name: 'Kigali Genocide Memorial', desc: 'A place of dignified remembrance. Guided tours are conducted respectfully.', image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAj6aIoBAgt21Bbyc-9-RFFE7UYTkUoJS8d8xrWKxmRPvySWjMpYF_TmEpQBk-M7j12Fkb-X9cJxmGiCwxpKY6SEq8dqEGvrdXZHbqb22zpryiWe9vk6hXSeuT-wKzeGwYQTlme8T9Tn4aZHpsDJZzEmRJNVgerrGWGD0Fs3SU6Ccsecd73yn1Axq28XdeJl5BnnHy_xgAhYx9R8tljcsAYvSGoGG9DkPyUfz8XnxQxIycJRzMBweOg3p8ag5_mUy78hoxpA2ayb9c', memorial: true },
      { name: 'Richard Kandt Museum', desc: 'The former home of Rwanda\'s first German resident, now a natural history museum.', image: '' },
      { name: 'Liberation Museum', desc: 'Learn about Rwanda\'s post-genocide reconstruction and reconciliation journey.', image: '' },
      { name: 'Nyandungu Eco Park', desc: 'A restored urban wetland and eco-park perfect for nature walks within Kigali.', image: '' },
      { name: 'Kigali City Tour', desc: 'Explore Kigali\'s vibrant markets, art galleries, and world-class coffee scene.', image: '' },
    ],
  },
]

export const corridorDataMap: Record<string, { title: string; description: string; image: string; packages: { name: string; desc: string }[] }> = {
  'northern-corridor': {
    title: 'Northern Corridor — Volcanoes National Park',
    description: 'The heart of Rwanda\'s conservation efforts and the majestic home of the mountain gorillas.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuCjINUSRFv7UittYpBJO6AAHXe3F0BQVZgbbW94jSc03juQ6_Hk20gQl-kYIK4-cWlQm7QCS1zjMzw75Ro6kZZWKAlB3-z9P-oqN_1ETtbsKB8G0YdUwSjzmxd5qJuj-zDhNKTAiklEmyeJ5C6SkvGddnafz_nokaD2P7UO4BPEzfpQmircKY934UXriV3-cwHqoKKIkDoht6ayxhfzkEDio8uVly4bhWBpP9k8MYyzt4kHA_Iwa07q_uX7hreGyFffWbqZwvildIg',
    packages: [
      { name: 'Gorilla Trekking', desc: 'Rwanda has 12 habituated gorilla families. Only 8 visitors per family per day, one-hour visits, minimum age 15.' },
      { name: 'Karisimbi Hiking', desc: 'Climb the highest Virunga volcano at 4,507m.' },
      { name: 'Bisoke Hiking', desc: 'Ascend to the stunning crater lake summit.' },
      { name: 'Gahinga Hiking', desc: 'Explore the extinct volcano\'s bamboo forest.' },
      { name: 'Sabyinyo Climbing', desc: 'Trek the "Old Man\'s Teeth" across three countries.' },
      { name: 'Iby\'Iwacu Cultural Village', desc: 'Immerse in traditional Rwandan village life.' },
      { name: 'Gorilla Museum', desc: 'Learn about conservation history at the volcanoes\' base.' },
      { name: 'Coffee Farm Tour Experience', desc: 'Visit coffee plantations for a crop-to-cup journey.' },
      { name: 'Twin Lakes', desc: 'Visit Lake Burera and Lake Ruhondo crater lakes.' },
    ],
  },
  'southern-corridor': {
    title: 'Southern Corridor',
    description: 'Rwanda\'s royal history and cultural heritage.',
    image: '',
    packages: [
      { name: 'King\'s Palace', desc: 'Visit the restored royal palace in Nyanza.' },
      { name: 'Ethnographic Museum', desc: 'Explore one of Africa\'s finest ethnographic museums in Huye.' },
      { name: 'Coffee Tour Experience', desc: 'Agrotourism in the southern coffee regions.' },
      { name: 'Murambi Genocide Memorial', desc: 'A dignified place of remembrance.' },
    ],
  },
  'nyungwe-forest': {
    title: 'Nyungwe Forest National Park',
    description: 'One of Africa\'s oldest rainforests, with 13 primate species and the famous canopy walkway.',
    image: '',
    packages: [
      { name: 'Chimpanzee Trekking', desc: 'Track habituated chimp troops.' },
      { name: 'Nyungwe Guided Nature Walks', desc: 'Explore ancient rainforest trails.' },
      { name: 'Nyungwe Bird Watching', desc: 'Spot 300+ bird species.' },
      { name: 'Nyungwe Canopy Walk', desc: 'Africa\'s highest canopy walkway at 50m.' },
      { name: 'Tropical Waterfall Guided Hike', desc: 'Hike to stunning waterfalls.' },
      { name: 'Congo Nile Divide Guided Hike', desc: 'Trek the continental divide.' },
    ],
  },
  'kivu-belt-road': {
    title: 'Kivu Belt Road',
    description: 'The most beautiful road in Rwanda, along Lake Kivu\'s sapphire waters.',
    image: '',
    packages: [
      { name: 'Boat Experience on Lake Kivu', desc: 'Sunset cruises and island-hopping from Karongi and Rubavu.' },
      { name: 'Island Visits on Lake Kivu', desc: 'Explore serene islands from Karongi.' },
    ],
  },
  'eastern-province': {
    title: 'Eastern Province — Akagera National Park',
    description: 'Big Five safaris in Rwanda\'s largest protected wetland.',
    image: '',
    packages: [
      { name: 'Akagera National Park', desc: 'Game drives and boat safaris. The Big Five await.' },
    ],
  },
  'kigali': {
    title: 'Kigali & Historical Legacies',
    description: 'Remembrance, reflection, and vibrant city culture.',
    image: '',
    packages: [
      { name: 'Kigali Genocide Memorial', desc: 'Dignified remembrance of the 1994 genocide.' },
      { name: 'Richard Kandt Museum', desc: 'Natural history in the first German resident\'s home.' },
      { name: 'Liberation Museum', desc: 'Rwanda\'s post-genocide reconstruction story.' },
      { name: 'Nyandungu Eco Park', desc: 'A restored urban wetland for nature walks.' },
      { name: 'Kigali City Tour', desc: 'Markets, galleries, and coffee scene.' },
    ],
  },
}
